//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int ID { get; set; }
        public System.Guid GUID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsCurrent { get; set; }
        public int Type { get; set; }
        public string Address { get; set; }
        public int Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public byte[] TMstamp { get; set; }
    }
}
