//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataTest
    {
        public int ID { get; set; }
        public Nullable<System.Guid> Guid { get; set; }
        public string Name { get; set; }
        public byte[] Data { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
