//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranBlobConfig
    {
        public int ID { get; set; }
        public System.Guid Guid { get; set; }
        public string TableName { get; set; }
        public string ColName { get; set; }
        public int Sort { get; set; }
        public byte Direct { get; set; }
        public Nullable<int> MaxCount { get; set; }
        public Nullable<long> Cstamp { get; set; }
        public Nullable<long> Sstamp { get; set; }
        public byte[] Timestamp { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    }
}
