//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranBlobConfig
    {
        public int ID { get; set; }
        public System.Guid Guid { get; set; }
        public string TableName { get; set; }
        public string ColName { get; set; }
        public int Sort { get; set; }
        public byte Direct { get; set; }
        public Nullable<int> MaxCount { get; set; }
        public Nullable<long> Cstamp { get; set; }
        public Nullable<long> Sstamp { get; set; }
        public byte[] Timestamp { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    }
}
