//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranConfig
    {
        public int ID { get; set; }
        public System.Guid Guid { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public int Sort { get; set; }
        public int MaxCount { get; set; }
        public Nullable<long> LastStamp { get; set; }
        public int Direct { get; set; }
        public string HeaderSql { get; set; }
        public string DetailSql { get; set; }
        public string FooterSql { get; set; }
        public string Remark { get; set; }
        public int Status { get; set; }
        public byte[] Timestamp { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
    }
}
