//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.Client.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ES.Client.ServiceReference.ArrayOfAnyType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ES.Client.ServiceReference.SqlData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ES.Client.ServiceReference.BlobData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ES.Client.ServiceReference.BlobData))]
    public partial class ResponseData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object dataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public object data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SqlData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SqlData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfigGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeaderSqlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailSqlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FooterSqlField;
        
        private int RowCountField;
        
        private long MaxTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ES.Client.ServiceReference.BlobData[] BlobDatasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ConfigGuid {
            get {
                return this.ConfigGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfigGuidField, value) != true)) {
                    this.ConfigGuidField = value;
                    this.RaisePropertyChanged("ConfigGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string HeaderSql {
            get {
                return this.HeaderSqlField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderSqlField, value) != true)) {
                    this.HeaderSqlField = value;
                    this.RaisePropertyChanged("HeaderSql");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DetailSql {
            get {
                return this.DetailSqlField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailSqlField, value) != true)) {
                    this.DetailSqlField = value;
                    this.RaisePropertyChanged("DetailSql");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FooterSql {
            get {
                return this.FooterSqlField;
            }
            set {
                if ((object.ReferenceEquals(this.FooterSqlField, value) != true)) {
                    this.FooterSqlField = value;
                    this.RaisePropertyChanged("FooterSql");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int RowCount {
            get {
                return this.RowCountField;
            }
            set {
                if ((this.RowCountField.Equals(value) != true)) {
                    this.RowCountField = value;
                    this.RaisePropertyChanged("RowCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public long MaxTimeStamp {
            get {
                return this.MaxTimeStampField;
            }
            set {
                if ((this.MaxTimeStampField.Equals(value) != true)) {
                    this.MaxTimeStampField = value;
                    this.RaisePropertyChanged("MaxTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public ES.Client.ServiceReference.BlobData[] BlobDatas {
            get {
                return this.BlobDatasField;
            }
            set {
                if ((object.ReferenceEquals(this.BlobDatasField, value) != true)) {
                    this.BlobDatasField = value;
                    this.RaisePropertyChanged("BlobDatas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlobData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BlobData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid GuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BlobField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Guid {
            get {
                return this.GuidField;
            }
            set {
                if ((this.GuidField.Equals(value) != true)) {
                    this.GuidField = value;
                    this.RaisePropertyChanged("Guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] Blob {
            get {
                return this.BlobField;
            }
            set {
                if ((object.ReferenceEquals(this.BlobField, value) != true)) {
                    this.BlobField = value;
                    this.RaisePropertyChanged("Blob");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.TransferSoap")]
    public interface TransferSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        global::ES.Client.ServiceReference.HelloWorldResponse HelloWorld(global::ES.Client.ServiceReference.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 clientCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ES.Client.ServiceReference.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ES.Client.ServiceReference.ResponseData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ES.Client.ServiceReference.SqlData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ES.Client.ServiceReference.BlobData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ES.Client.ServiceReference.BlobData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Guid))]
        global::ES.Client.ServiceReference.GetResponse Get(global::ES.Client.ServiceReference.GetRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 clientCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Post", ReplyAction="*")]
        global::ES.Client.ServiceReference.PostResponse Post(global::ES.Client.ServiceReference.PostRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 clientCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTranConfigs", ReplyAction="*")]
        global::ES.Client.ServiceReference.GetTranConfigsResponse GetTranConfigs(global::ES.Client.ServiceReference.GetTranConfigsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public global::ES.Client.ServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(global::ES.Client.ServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public global::ES.Client.ServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(global::ES.Client.ServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get", Namespace="http://tempuri.org/", Order=0)]
        public global::ES.Client.ServiceReference.GetRequestBody Body;
        
        public GetRequest() {
        }
        
        public GetRequest(global::ES.Client.ServiceReference.GetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string varifyCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long lastTimeStamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int rowCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string configGuid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ES.Client.ServiceReference.ArrayOfAnyType paras;
        
        public GetRequestBody() {
        }
        
        public GetRequestBody(string clientCode, string varifyCode, long lastTimeStamp, int rowCount, string configGuid, ES.Client.ServiceReference.ArrayOfAnyType paras) {
            this.clientCode = clientCode;
            this.varifyCode = varifyCode;
            this.lastTimeStamp = lastTimeStamp;
            this.rowCount = rowCount;
            this.configGuid = configGuid;
            this.paras = paras;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResponse", Namespace="http://tempuri.org/", Order=0)]
        public global::ES.Client.ServiceReference.GetResponseBody Body;
        
        public GetResponse() {
        }
        
        public GetResponse(global::ES.Client.ServiceReference.GetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ES.Client.ServiceReference.ResponseData GetResult;
        
        public GetResponseBody() {
        }
        
        public GetResponseBody(ES.Client.ServiceReference.ResponseData GetResult) {
            this.GetResult = GetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Post", Namespace="http://tempuri.org/", Order=0)]
        public global::ES.Client.ServiceReference.PostRequestBody Body;
        
        public PostRequest() {
        }
        
        public PostRequest(global::ES.Client.ServiceReference.PostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string varifyCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ES.Client.ServiceReference.SqlData data;
        
        public PostRequestBody() {
        }
        
        public PostRequestBody(string clientCode, string varifyCode, ES.Client.ServiceReference.SqlData data) {
            this.clientCode = clientCode;
            this.varifyCode = varifyCode;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostResponse", Namespace="http://tempuri.org/", Order=0)]
        public global::ES.Client.ServiceReference.PostResponseBody Body;
        
        public PostResponse() {
        }
        
        public PostResponse(global::ES.Client.ServiceReference.PostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ES.Client.ServiceReference.ResponseData PostResult;
        
        public PostResponseBody() {
        }
        
        public PostResponseBody(ES.Client.ServiceReference.ResponseData PostResult) {
            this.PostResult = PostResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTranConfigsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTranConfigs", Namespace="http://tempuri.org/", Order=0)]
        public global::ES.Client.ServiceReference.GetTranConfigsRequestBody Body;
        
        public GetTranConfigsRequest() {
        }
        
        public GetTranConfigsRequest(global::ES.Client.ServiceReference.GetTranConfigsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTranConfigsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string varifyCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long timestamp;
        
        public GetTranConfigsRequestBody() {
        }
        
        public GetTranConfigsRequestBody(string clientCode, string varifyCode, long timestamp) {
            this.clientCode = clientCode;
            this.varifyCode = varifyCode;
            this.timestamp = timestamp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTranConfigsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTranConfigsResponse", Namespace="http://tempuri.org/", Order=0)]
        public global::ES.Client.ServiceReference.GetTranConfigsResponseBody Body;
        
        public GetTranConfigsResponse() {
        }
        
        public GetTranConfigsResponse(global::ES.Client.ServiceReference.GetTranConfigsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTranConfigsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ES.Client.ServiceReference.ResponseData GetTranConfigsResult;
        
        public GetTranConfigsResponseBody() {
        }
        
        public GetTranConfigsResponseBody(ES.Client.ServiceReference.ResponseData GetTranConfigsResult) {
            this.GetTranConfigsResult = GetTranConfigsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TransferSoapChannel : global::ES.Client.ServiceReference.TransferSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransferSoapClient : System.ServiceModel.ClientBase<global::ES.Client.ServiceReference.TransferSoap>, global::ES.Client.ServiceReference.TransferSoap {
        
        public TransferSoapClient() {
        }
        
        public TransferSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransferSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransferSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransferSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::ES.Client.ServiceReference.HelloWorldResponse global::ES.Client.ServiceReference.TransferSoap.HelloWorld(global::ES.Client.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            global::ES.Client.ServiceReference.HelloWorldRequest inValue = new global::ES.Client.ServiceReference.HelloWorldRequest();
            inValue.Body = new global::ES.Client.ServiceReference.HelloWorldRequestBody();
            global::ES.Client.ServiceReference.HelloWorldResponse retVal = ((global::ES.Client.ServiceReference.TransferSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::ES.Client.ServiceReference.GetResponse global::ES.Client.ServiceReference.TransferSoap.Get(global::ES.Client.ServiceReference.GetRequest request) {
            return base.Channel.Get(request);
        }
        
        public ES.Client.ServiceReference.ResponseData Get(string clientCode, string varifyCode, long lastTimeStamp, int rowCount, string configGuid, ES.Client.ServiceReference.ArrayOfAnyType paras) {
            global::ES.Client.ServiceReference.GetRequest inValue = new global::ES.Client.ServiceReference.GetRequest();
            inValue.Body = new global::ES.Client.ServiceReference.GetRequestBody();
            inValue.Body.clientCode = clientCode;
            inValue.Body.varifyCode = varifyCode;
            inValue.Body.lastTimeStamp = lastTimeStamp;
            inValue.Body.rowCount = rowCount;
            inValue.Body.configGuid = configGuid;
            inValue.Body.paras = paras;
            global::ES.Client.ServiceReference.GetResponse retVal = ((global::ES.Client.ServiceReference.TransferSoap)(this)).Get(inValue);
            return retVal.Body.GetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::ES.Client.ServiceReference.PostResponse global::ES.Client.ServiceReference.TransferSoap.Post(global::ES.Client.ServiceReference.PostRequest request) {
            return base.Channel.Post(request);
        }
        
        public ES.Client.ServiceReference.ResponseData Post(string clientCode, string varifyCode, ES.Client.ServiceReference.SqlData data) {
            global::ES.Client.ServiceReference.PostRequest inValue = new global::ES.Client.ServiceReference.PostRequest();
            inValue.Body = new global::ES.Client.ServiceReference.PostRequestBody();
            inValue.Body.clientCode = clientCode;
            inValue.Body.varifyCode = varifyCode;
            inValue.Body.data = data;
            global::ES.Client.ServiceReference.PostResponse retVal = ((global::ES.Client.ServiceReference.TransferSoap)(this)).Post(inValue);
            return retVal.Body.PostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::ES.Client.ServiceReference.GetTranConfigsResponse global::ES.Client.ServiceReference.TransferSoap.GetTranConfigs(global::ES.Client.ServiceReference.GetTranConfigsRequest request) {
            return base.Channel.GetTranConfigs(request);
        }
        
        public ES.Client.ServiceReference.ResponseData GetTranConfigs(string clientCode, string varifyCode, long timestamp) {
            global::ES.Client.ServiceReference.GetTranConfigsRequest inValue = new global::ES.Client.ServiceReference.GetTranConfigsRequest();
            inValue.Body = new global::ES.Client.ServiceReference.GetTranConfigsRequestBody();
            inValue.Body.clientCode = clientCode;
            inValue.Body.varifyCode = varifyCode;
            inValue.Body.timestamp = timestamp;
            global::ES.Client.ServiceReference.GetTranConfigsResponse retVal = ((global::ES.Client.ServiceReference.TransferSoap)(this)).GetTranConfigs(inValue);
            return retVal.Body.GetTranConfigsResult;
        }
    }
}
